### PR TITLE
Remove unneeded function argument

### PR DESCRIPTION
**Pull request by JohnScott623**
This resolves warnings that some C++ compilers may show.

### CODE REVIEW

**Comment by haikarainen** [comment]
I'm not sure how well this would work with QtCreator. Have you tested it?

**Comment by JohnScott623** [comment]
I have. My C++ compiler issued several warnings stating that the argument was not needed, which already meant that removing it should do nothing. I've compiled and run it on my system, and it seems to not make a difference at run-time.

**Comment by haikarainen** [comment]
Let's leave this open until I've got the time to do further testing! 

Also, thanks for contributing, always very appreciated! :+1:

**Comment by haikarainen** [comment]
As suspected, removing the parameter messes with QtCreator.  These warnings are pretty harmless in this case though, since the compiler will optimize away the unused parameters.

**Pull request closed without merging**
